### ISSUE TITLE
Browserless is unable to access another service running on the same docker network

### ISSUE THREAD

**Issue by AmruthPillai** [browserless/browserless#3676]
**Describe the bug**

I'll try to keep this short and concise. I don't think it's an issue with browserless, but probably some flag that I would need to activate for it to work as expected.

Right now, I have this docker compose setup.

```
version: "3"

services:
  ...

  chrome:
    image: browserless/chrome:1.61.0-puppeteer-21.4.1
    restart: always
    environment:
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true
      DEFAULT_IGNORE_HTTPS_ERRORS: true
      TOKEN: some_long_32_token
    labels:
      - traefik.enable=true
      - traefik.http.routers.printer.rule=Host(`printer.example.com`)
      - traefik.http.routers.printer.entrypoints=websecure
      - traefik.http.routers.printer.tls.certresolver=letsencrypt
      - traefik.http.services.printer.loadbalancer.server.port=3000

  # This is a simple node server image with puppeteer installed
  # attempting to connect to the browserless instance
  app:
    image: custom-image:latest
    ...
    environment:
      CHROME_URL: ws://chrome:3000?token=some_long_32_token
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`example.com`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls.certresolver=letsencrypt
      - traefik.http.services.app.loadbalancer.server.port=3000

  traefik:
    image: traefik
    command:
      - --api=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=noreply@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

      # Redirect all HTTP requests to HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  ...
```

Now, the issue is: The server image is able to connect to the browser instance just fine if I use the CHROME_URL pointed to `ws://chrome:3000`. But it doesn't work if it's pointed to `wss://printer.example.com`.

Also, inside the browser debugger, I tested whether I was able to access `example.com` but it failed. Instead, if I were to host the app elsewhere and get a different URL, it does work. What can I do to make these services speak to each other as intended?

**To Reproduce**

I'm not sure how easy it would be to reproduce, but I am building all of this open-source, so you can check the docker-compose file here: https://github.com/AmruthPillai/Reactive-Resume/blob/v4/tools/compose/traefik-secure.yml
