### ISSUE TITLE
Arm64 docker image gives "Error: Couldn't load route "/content" on launch

### ISSUE THREAD

**Issue by akutruff** [browserless/browserless#3797]
**Describe the bug**

I pulled the latest version and received the following logs:

sidewalk-browserless  | Please use variable name "TIMEOUT" in place of "CONNECTION_TIMEOUT"
sidewalk-browserless  |   browserless.io:limiter Concurrency: 10 queue: 10 timeout: 480000ms +0ms
sidewalk-browserless  |   browserless.io:index 
sidewalk-browserless  |   browserless.io:index ---------------------------------------------------------
sidewalk-browserless  |   browserless.io:index | browserless.io
sidewalk-browserless  |   browserless.io:index | To read documentation and more, load in your browser:
sidewalk-browserless  |   browserless.io:index |
sidewalk-browserless  |   browserless.io:index | http://0.0.0.0:3000/docs
sidewalk-browserless  |   browserless.io:index ---------------------------------------------------------
...
sidewalk-browserless  |   browserless.io:index  +0ms
sidewalk-browserless  |   browserless.io:index Running as user "blessuser" +6ms
sidewalk-browserless  |   browserless.io:index Starting import of HTTP Routes +0ms
sidewalk-browserless  |   browserless.io:index Starting import of WebSocket Routes +300ms
sidewalk-browserless  | Unhandled Rejection at: Promise {
sidewalk-browserless  |   <rejected> Error: Couldn't load route "/content" due to missing browser of "CDPChromium"
sidewalk-browserless  |       at file:///usr/src/app/build/browserless.js:145:23
sidewalk-browserless  |       at Array.forEach (<anonymous>)
sidewalk-browserless  |       at Browserless.start (file:///usr/src/app/build/browserless.js:141:38)
sidewalk-browserless  | } reason: Error: Couldn't load route "/content" due to missing browser of "CDPChromium"
sidewalk-browserless  |     at file:///usr/src/app/build/browserless.js:145:23
sidewalk-browserless  |     at Array.forEach (<anonymous>)
sidewalk-browserless  |     at Browserless.start (file:///usr/src/app/build/browserless.js:141:38)
sidewalk-browserless  |   browserless.io:index.js Process is finished, exiting +0ms

**To Reproduce**
1.  Launch the arm64 image.

compose file
```
version: "3.9"

services:
  browserless:
    image: ghcr.io/browserless/chrome
    restart: always
    environment:
      - TZ=America/New_York
      - CONNECTION_TIMEOUT=480000
      - TOKEN=xxxxx
    ports:
      - 3000:3000
    volumes:
      - nas:/data
    network_mode: "host"

volumes:
  nas:
    driver_opts:
      type: cifs
      o: "username=${NAS_USERNAME},password=${NAS_PASSWORD},addr=${NAS_ADDR},vers=3.02,mfsymlinks,file_mode=0777,dir_mode=0777"
      device: "${NAS_PATH}"
```

**Expected behavior**
container runs normally

**Desktop (please complete the following information):**
arm64
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
