### ISSUE TITLE
Architecture issue on Raspberry Pi

### ISSUE THREAD

**Issue by QuinnyPig** [browserless/browserless#3803]
There's something odd about the arm64 images being built and pushed to Docker hub.

On a 64-bit Raspian install on a Raspberry Pi 4:

`docker run  --platform linux/arm64 browserless/base` works correctly.
`docker run  --platform linux/arm64 browserless/chrome` throws:
exec ./start.sh: exec format error

linux/arm64 and linux/arm/v8 are supposedly identical architectures; am I missing something obvious here?

**Comment by joelgriffith** [comment]
Have you tried it on V2? Just want to verify the version you're on, which looks like V2 but wanted to check

**Comment by jeayalar** [comment]
Hi @joelgriffith!

I'm having the same issue as @QuinnyPig, although not in a Raspberry Pi, I do use the browserless/chrome linux/arm64 image on an Oracle free tier server. I've used the following docker compose file to pull the image:

```
version: "3.8"

networks:
  browserless:

services:
  browserless:
    container_name: browserless
    environment:
      TOKEN: ${BROWSERLESS_TOKEN}
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true
    hostname: browserless
    image: browserless/chrome:latest
    networks:
      - browserless
    ports:
      - 127.0.0.1:9985:3000
    restart: always
```

Similar to @QuinnyPig, my logs are filled with `exec ./start.sh: exec format error`.

```
docker logs browserless --follow

exec ./start.sh: exec format error
exec ./start.sh: exec format error
exec ./start.sh: exec format error
exec ./start.sh: exec format error
exec ./start.sh: exec format error
```

Let me know if you need me to provide more information.
