### ISSUE TITLE
Browser keeps getting closed after exactly 300 seconds since starting the job

### ISSUE THREAD

**Issue by aalfath** [browserless/browserless#3831]
**Describe the bug**
CONNECTION_TIMEOUT environment variable doesn't seem to work.

**To Reproduce**
1. Use this docker image: ghcr.io/browserless/chrome:latest
2. Added environment variable on Kubernetes, like in below example:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chrome-microservice
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/browserless/chrome:latest
          name: chrome
          imagePullPolicy: Always
          env:
            - name: CONCURRENT
              value: "1"
            - name: MAX_QUEUE_LENGTH
              value: "0"
            - name: SINGLE_RUN
              value: "true"
            - name: TIMEOUT
              value: "1800000"
            - name: CONNECTION_TIMEOUT
              value: "1800000"
            - name: EXIT_ON_HEALTH_FAILURE
              value: "false"
          ports:
            - containerPort: 3000
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
```
3. Invoke the browser via websocket from a Puppeteer instance
4. The browser in Docker seems to be closed right after 5 minutes (300 seconds), this produces either "Target closed" or "Requesting main frame too early!" error on Puppeteer.

**Expected behavior**
The browser's session should stay opened according to the CONNECTION_TIMEOUT environment variable.
Please check the below log, specifically on line that says `browserless.io:limiter Job has succeeded after 299,913ms of activity`
This seems to indicate that something must have configured the browser's session to be limited to exactly or around 300 seconds.

**Logs from Docker container**
```
Please use variable name "TIMEOUT" in place of "CONNECTION_TIMEOUT"
  browserless.io:limiter Concurrency: 1 queue: 10 timeout: 1800000ms +0ms
  browserless.io:index 
  browserless.io:index ---------------------------------------------------------
  browserless.io:index | browserless.io
  browserless.io:index | To read documentation and more, load in your browser:
  browserless.io:index |
  browserless.io:index | http://0.0.0.0:3000/docs
  browserless.io:index ---------------------------------------------------------
  browserless.io:index 
  browserless.io:index 
  browserless.io:index █▓▒
  browserless.io:index ████▒
  browserless.io:index ████▒
  browserless.io:index ████▒   ▒██▓▒
  browserless.io:index ████▒   ▒████
  browserless.io:index ████▒   ▒████
  browserless.io:index ████▒   ▒████
  browserless.io:index ████▒   ▒████
  browserless.io:index ████▒   ▒████
  browserless.io:index ████▒   ▒██████▓▒
  browserless.io:index ████▒   ▒██████████▒
  browserless.io:index ████▒   ▒██████▓████
  browserless.io:index ████▒   ▒█▓▓▒  ▒████
  browserless.io:index ████▒          ▒████
  browserless.io:index ████▒       ▒▓██████
  browserless.io:index ████▒   ▒▓████████▓▒
  browserless.io:index ████▓▓████████▓▒
  browserless.io:index ██████████▓▒
  browserless.io:index   ▓███▓▒
  browserless.io:index 
  browserless.io:index  +0ms
  browserless.io:index Running as user "blessuser" +2ms
  browserless.io:index Starting import of HTTP Routes +0ms
  browserless.io:index Starting import of WebSocket Routes +73ms
  browserless.io:index Imported and validated all route files, starting up server. +6ms
  browserless.io:server Server instantiated with host "0.0.0.0" on port "3000" using token "xxxxx" +0ms
  browserless.io:server HTTP Server is starting +1ms
  browserless.io:server HTTP Server is listening on http://0.0.0.0:3000
  browserless.io:server Use http://0.0.0.0:3000 for API and connect calls +2ms
  browserless.io:index Starting metrics collection. +4ms
  browserless.io:limiter (Running: 0, Pending: 0) Adding to queue, max time allowed is 1,800,000ms  +1m
  browserless.io:limiter (Running: 1, Pending: 0) Starting new job  +2ms
  browserless.io:browser-manager Generating user-data-dir at /tmp/browserless-data-dirs/browserless-data-dir-dff5dedb-b96d-4e2f-893a-06939a0cd899 +0ms
  browserless.io:browsers:cdp:chromium Starting new browser instance +0ms
  browserless.io:browsers:cdp:chromium Got open port 34371 +3ms
  browserless.io:browsers:cdp:chromium {
  browserless.io:browsers:cdp:chromium   args: [
  browserless.io:browsers:cdp:chromium     '--remote-debugging-port=34371',
  browserless.io:browsers:cdp:chromium     '--no-sandbox',
  browserless.io:browsers:cdp:chromium     '--window-size=1920,1080',
  browserless.io:browsers:cdp:chromium     '--user-data-dir=/tmp/browserless-data-dirs/browserless-data-dir-dff5dedb-b96d-4e2f-893a-06939a0cd899'
  browserless.io:browsers:cdp:chromium   ],
  browserless.io:browsers:cdp:chromium   executablePath: '/usr/local/bin/playwright-browsers/chromium-1097/chrome-linux/chrome'
  browserless.io:browsers:cdp:chromium } Launching CDP Chrome Handler +1ms
  browserless.io:browsers:cdp:chromium Browser is running on ws://127.0.0.1:34371/devtools/browser/0ab4b9f7-6ecc-4a9f-9b5a-4347402122ea +561ms
  browserless.io:browsers:cdp:chromium Proxying http://0.0.0.0:3000/?launch=%7B%22args%22%3A%5B%22--window-size%3D1920%2C1080%22%5D%7D to browser ws://127.0.0.1:34371/devtools/browser/0ab4b9f7-6ecc-4a9f-9b5a-4347402122ea +3ms
  browserless.io:browsers:cdp:chromium Setting up file:// protocol request rejection +158ms
  browserless.io:error No handler or file found for resource / +0ms
  browserless.io:index Current period usage: {"date":1706998315099,"error":0,"maxConcurrent":1,"maxTime":null,"meanTime":0,"minTime":null,"rejected":0,"successful":0,"timedout":0,"totalTime":0,"units":0} +5m
  browserless.io:index Saving metrics to "/tmp/browserless-metrics.json" +2ms
  browserless.io:browser-manager 0 Client(s) are currently connected +5m
  browserless.io:browser-manager Closing browser session +0ms
  browserless.io:browser-manager Deleting "/tmp/browserless-data-dirs/browserless-data-dir-dff5dedb-b96d-4e2f-893a-06939a0cd899" user-data-dir and session from memory +0ms
  browserless.io:browsers:cdp:chromium Closing browser process and all listeners +5m
  browserless.io:limiter Job has succeeded after 299,913ms of activity. +5m
  browserless.io:limiter (Running: 0, Pending: 0) All jobs complete.  +1ms
  browserless.io:browser-manager Deleting data directory "/tmp/browserless-data-dirs/browserless-data-dir-dff5dedb-b96d-4e2f-893a-06939a0cd899" +36ms
  browserless.io:index Current period usage: {"date":1706998615111,"error":0,"maxConcurrent":0,"maxTime":299913,"meanTime":299913,"minTime":299913,"rejected":0,"successful":1,"timedout":0,"totalTime":299913,"units":10} +5m
  browserless.io:index Saving metrics to "/tmp/browserless-metrics.json" +3ms
```
