### ISSUE TITLE
docker container crashes when using custom user

### ISSUE THREAD

**Issue by ingria** [browserless/browserless#4018]
**Describe the bug**
Setting `user` param in docker config causes this error:

```
  browserless.io:index 
  browserless.io:index  +0ms
Unhandled Rejection at: Promise {
  <rejected> SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
      at userInfo (node:os:365:11)
      at Browserless.start (file:///usr/src/app/build/browserless.js:132:40) {
    code: 'ERR_SYSTEM_ERROR',
    info: {
      errno: -2,
      code: 'ENOENT',
      message: 'no such file or directory',
      syscall: 'uv_os_get_passwd'
    },
    errno: [Getter/Setter: -2],
    syscall: [Getter/Setter: 'uv_os_get_passwd']
  }
} reason: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at userInfo (node:os:365:11)
    at Browserless.start (file:///usr/src/app/build/browserless.js:132:40) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -2,
    code: 'ENOENT',
    message: 'no such file or directory',
    syscall: 'uv_os_get_passwd'
  },
  errno: [Getter/Setter: -2],
  syscall: [Getter/Setter: 'uv_os_get_passwd']
}
  browserless.io:index.js Process is finished, exiting +0ms
```

**To Reproduce**
Run the following docker compose file:

```yaml
services:
  browserless:
    container_name: browserless
    image: ghcr.io/browserless/chromium
    network_mode: host
    restart: unless-stopped
    user: "1001:1001"
    privileged: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TOKEN: test
    deploy:
      resources:
        limits:
          memory: 8G
    logging:
      driver: json-file
      options:
        max-size: 1G
        max-file: 2
```

**Expected behavior**
Container runs under 1001:1001 user

**Screenshots**
n/a
