### ISSUE TITLE
Error: "browserless:server /: Forbidden. Behavior of "http" set, writing response and closing." running browserless in docker

### ISSUE THREAD

**Issue by Dominik-Reinert** [browserless/browserless#4029]
I added browserless as a service to my docker compose file in order for [big-agi](https://github.com/enricoros/big-AGI) to browse websites and show e.g. previews.

When pasting a url into the input prompt, I get an error in the UI and the docker logs of the browserless service adds a single line:

`2024-05-05T08:20:56.916Z browserless:server /: Forbidden. Behavior of "http" set, writing response and closing`

Adding the debug logs flag does not give any more details. It just fails and I cannot find anywhere, what this error is even supposed to do.

**To Reproduce**

- set up big agi
- set up browserless
- paste a url into the input prompt

```
  browserless:
    image: browserless/chrome:1-chrome-stable
    ports:
      - "9222:3000"
    env_file:
      - .env
    environment:
      - TOKEN=${BROWSERLESS_TOKEN}
      - CORS=true
      - CORS_ALLOW_METHODS=POST, GET, DELETE
      - ALLOW_GET=true
    networks:
      - big-agi-internal
```

**Expected behavior**

The preview to work or to get a meaningful error message

**Screenshots**

![image](https://github.com/browserless/browserless/assets/48657257/f9ec75cd-3e1b-48b0-91a1-016dd72e7d8a)

**Desktop (please complete the following information):**

- OS: docker
- Browser chrome
