### ISSUE TITLE
can't reconnect to existing session, docker

### ISSUE THREAD

**Issue by opadfnezig** [browserless/browserless#4149]
Using latest chrome image. Cannot reconnect.

```
docker run -e "TIMEOUT=60000" -p 3000:3000 ghcr.io/browserless/chromium
```
as mentioned in documentation won't do anything to me. It seems like sessions are being killed immidiately after I disconnect from instance (I'm not closing browser).

Sometimes it's still in the sessions, but after I try to reconnect - it's recreated.

```
services:
  puppet:
    image: ghcr.io/browserless/chrome:latest
    environment:
      - TIMEOUT=600000
      - CONNECTION_TIMEOUT=600000
      - TOKEN=6R0W53R135510
    ports:
      - 30000:3000
```
this is my comsose. As you can see I'm using both TIMEOUT and CONNECTION_TIMEOUT(found it in old issue), doesn't do anything to me. Also tried putting timeout into query parameters, into launch args, setting ttl the same way. Nothing helps.
